name: 'Gene_Expression_PCA_Heatmap_Cluster'
description: 'Do PCA heatmap and sample cluster for a gene expression matrix'
inputs:
  fpkm:  # fpkm matrix file path
    description: 'the file path of fpkm matrix'
    required: true
    default: 'fpkm.xls'

  group:  # sample group file path
    description: 'the file path of sample group'
    required: true
    default: 'group.txt'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.fpkm }} ${{ inputs.fpkm }}
