name: 'Gene_Expression_PCA_Heatmap_Cluster'
description: 'Do PCA heatmap and sample cluster for a gene expression matrix'
inputs:
  fpkm:  # fpkm matrix file path
    description: 'the file path of fpkm matrix'
    required: true
    default: 'fpkm.xls'

  group:  # sample group file path
    description: 'the file path of sample group'
    required: true
    default: 'group'

outputs:
  outfile: 
    description: "out put pdf file"
    value: "pca.pdf"

runs:
  using: "composite"
  steps: 
    - id: Do-PCA
      run: Rscript FPKM_PCA_Heatmap_Cluster.R ${{ inputs.fpkm }} ${{ inputs.group }}
      shell: bash

